version: '3.8'

services:
    app:
        image: nginx:latest
        ports:
            - "9080:9080"
        environment:
            - ENV=production
        volumes:
            - ./app:/usr/src/app

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
